server:
  port: 8080

logging:
  level:
    com.wanel.mocking.kyx.server: INFO
    org.springframework: INFO

spring:
  application:
    name: mock-kyx-api-server

# Default configuration for Python script execution
kyx:
  python:
    script-path: ${user.home}/kyx_script.py
    function-name: kyxCheck
  providers:
    - name: goplus
      enabled: true
    - name: chainalysis
      enabled: true 